# Supplementary Figures

## Defining some Fun-ctions

```{r, warning=FALSE, message=FALSE, tidy=TRUE,cache=FALSE}
library(openxlsx) 
library(ggplot2)
library(ggrepel)
library(ggbreak) 
library(patchwork)
library(dplyr)
library(stringr)
library(lubridate)
library(cowplot)
library(readxl)
library(gtable)
library(gridExtra)
library(ggpubr)
library(grid)  


RowCounts <- function(ClassData, Title, bin = NULL, mode = 'Doc') {
  lineCounts <- sort(table(ClassData$prj))
  
  
  
  count_df <- data.frame(Prj = names(lineCounts), Count = as.vector(lineCounts))
  count_df$date <- metaData$prjDate[match(count_df$Prj, metaData$prjCode)]
  count_df$dateSAP <- metaData$SAPprjDate[match(count_df$Prj, metaData$prjCode)]
  count_df$Dev <- metaData$Developer[match(count_df$Prj, metaData$prjCode)]
  count_df$Doc <- metaData$DocType[match(count_df$Prj, metaData$prjCode)]
  count_df$Consult <- metaData$Consultantcy[match(count_df$Prj, metaData$prjCode)]
  prjNames <- unique(classData$prj)
  for (i in prjNames){
    if (!(i %in% as.vector(count_df$Prj))){
      count_df <- rbind(count_df, data.frame(
        Prj = i, 
        Count = 0, 
        date = metaData$prjDate[match(i, metaData$prjCode)],
        dateSAP = metaData$SAPprjDate[match(i, metaData$prjCode)],
        Dev = metaData$Developer[match(i, metaData$prjCode)], 
        Doc = metaData$DocType[match(i, metaData$prjCode)],
        Consult = metaData$Consultantcy[match(i, metaData$prjCode)]))
    }
  }
  if ("BIW" %in% count_df$Prj){ 
    count_df$date[count_df$Prj == "BIW"] <- as.character('10/01/2020')
    count_df$dateSAP[count_df$Prj == "BIW"] <- as.character('10/01/2015')
  }
  
  count_df$date <- as.Date(count_df$date, format = "%m/%d/%Y")
  count_df$dateSAP <- as.Date(count_df$dateSAP, format = "%m/%d/%Y")
  count_df <- data.frame(count_df[order(count_df$date),], row.names = NULL)
  
  plt<-ggplot(count_df, aes(date, Count, label = Prj, color = Dev, shape = Doc))+
    geom_point(show.legend = FALSE)+ geom_text_repel(show.legend = FALSE)+theme_classic()+
    labs(title = Title, x ="Document release date", y = "Count", color = "Developer", shape = "Document")
  pltSAP<-ggplot(count_df, aes(dateSAP, Count, label = Prj, color = Dev, shape = Doc))+
    geom_point()+ geom_text_repel(show.legend = FALSE)+theme_classic()+
    labs(title = Title, x ="SAP release date", y = "Count", color = "Developer", shape = "Document")  
  
  
  # if (!is.null(bin)){
  #   ap <- data.frame(title= Title, Cor = cor(as.numeric(count_df$date), count_df$Count), type = "#")
  #   bin<<-rbind(bin, ap)
  # }
  
  if ("BIW" %in% count_df$Prj){ 
    plt<-plt + geom_segment(aes(
      x=date[Prj == "BIW"], 
      y=Count[Prj == "BIW"], 
      xend=as.Date(-Inf), 
      yend=Count[Prj == "BIW"]),
      color = 'black',
      arrow = arrow(length=unit(0.5, 'cm')))
    pltSAP<-pltSAP + geom_segment(aes(
      x=dateSAP[Prj == "BIW"], 
      y=Count[Prj == "BIW"], 
      xend=as.Date(-Inf), 
      yend=Count[Prj == "BIW"]),
      color = 'black',
      arrow = arrow(length=unit(0.5, 'cm')))
  }
  if (mode == 'SAP'){
    return(pltSAP)}else{
      return(plt)}
}
RowCountsFreq <- function(OgClassData, ClassData, Title, bin = NULL) {
  lineCounts <- table(ClassData$prj)
  lineCounts <- data.frame(Prj = names(lineCounts), Count = as.vector(lineCounts))
  OglineCounts <- table(OgClassData$prj)
  OglineCounts <- data.frame(Prj = names(OglineCounts), Count = as.vector(OglineCounts))
  
  OglineCounts <- OglineCounts[OglineCounts$Prj %in% lineCounts$Prj, ]
  count_df <- data.frame(Prj = lineCounts$Prj, Count = lineCounts$Count, OgCount = OglineCounts$Count)
  count_df$freq <- (count_df$Count / count_df$OgCount) * 100
  count_df$date <- metaData$prjDate[match(count_df$Prj, metaData$prjCode)]
  count_df$Dev <- metaData$Developer[match(count_df$Prj, metaData$prjCode)]
  count_df$Doc <- metaData$DocType[match(count_df$Prj, metaData$prjCode)]
  count_df$Consult <- metaData$Consultantcy[match(count_df$Prj, metaData$prjCode)]
  prjNames <- unique(classData$prj)
  
  for (i in prjNames){
    if (!(i %in% as.vector(count_df$Prj))){
      count_df <- rbind(count_df, data.frame(Prj = i, 
                                             Count = 0, 
                                             OgCount =0,
                                             freq = 0, 
                                             date = metaData$prjDate[match(i, metaData$prjCode)], 
                                             Dev = metaData$Developer[match(i, metaData$prjCode)], 
                                             Doc = metaData$DocType[match(i, metaData$prjCode)],
                                             Consult = metaData$Consultantcy[match(i, metaData$prjCode)]))
    }
  }
  
  if ("BIW" %in% count_df$Prj){ 
    count_df$date[count_df$Prj == "BIW"] <- as.character('10/01/2020')
  }
  
  count_df$date <- as.Date(count_df$date, format = "%m/%d/%Y")
  count_df <- data.frame(count_df[order(count_df$date),], row.names = NULL)
  
  plt<-ggplot(count_df, aes(date, freq, label = Prj, color = Dev, shape = Doc))+
    geom_point(show.legend = FALSE)+ geom_text_repel(show.legend = FALSE)+theme_classic()+
    labs(title = Title, x ="Document release date", y = "frequency %", color = "Developer", shape = "Document")
  
  if (!is.null(bin)){
    ap <- data.frame(title= Title, Cor = cor(as.numeric(count_df$date), count_df$freq), type = "%")
    bin<<-rbind(bin, ap)
  }
  if ("BIW" %in% count_df$Prj){ 
    plt<-plt + geom_segment(aes(
      x=date[Prj == "BIW"], 
      y=freq[Prj == "BIW"], 
      xend=as.Date(-Inf), 
      yend=freq[Prj == "BIW"]),
      color = 'black',
      arrow = arrow(length=unit(0.5, 'cm')))
  }
  return(plt)
}
RowHist <- function(ClassData, Title) {
  lineCounts <- sort(table(ClassData$prj))
  
  
  
  count_df <- data.frame(Prj = names(lineCounts), Count = as.vector(lineCounts))
  count_df$date <- metaData$prjDate[match(count_df$Prj, metaData$prjCode)]
  count_df$date <- as.Date(count_df$date, format = "%m/%d/%Y")
  
  # Create intervals using cut()
  cuts <- cut(count_df$date, breaks = '3 months')
  interval_labels <- as.Date(levels(cuts))
  
  # Calculate the mean of Count within each interval
  mean_values <- aggregate(Count ~ cuts, data = count_df, FUN = mean)
  
  # Create a complete set of intervals
  all_intervals <- data.frame(cuts = levels(cuts))
  
  # Merge mean_values with all_intervals, filling missing values with 0
  mean_values_complete <- merge(all_intervals, mean_values, by = "cuts", all.x = TRUE)
  mean_values_complete[is.na(mean_values_complete)] <- 0
  
  # Plot the histogram with mean values
  plt<- ggplot(mean_values_complete, aes(cuts, Count)) +
    geom_histogram(stat = 'identity') +
    labs(x = "Time", y = "Count", title = Title) +
    theme_classic()+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
  
  return(plt)
}
```

## Importing Data

```{r, warning=FALSE, message=FALSE, tidy=TRUE,cache=FALSE}
file_path <- "./ClassificationData.xlsx"

classData <- read_excel(file_path, sheet = 1) #Grabbing the data from excel
metaData <- read_excel(file_path, sheet = 2) #Grabbing the data from excel

classData$prj <- substr(classData$Code,1,3)
classData$comit <- as.numeric(substr(classData$Code,4,4))

classData$date <- metaData$prjDate[match(classData$prj, metaData$prjCode)]
classData$date <- as.Date(classData$date, format = "%m/%d/%Y")
```

## By Protected Resource

```{r, warning=FALSE, message=FALSE, tidy=TRUE,cache=FALSE}
recource <- c("MarineMams", "Turts", "Birds", "Bats", "Benthic", "AirQ", "WaterQ", "AcouAbove", "AcouBelow","Fish", "EssFishHabs", "CultArcheo", "CoastalHabs", "WetLands", "RecTourism", "RecComFisheries","VesselNav", "SocioEcon", "EnviroJustice", "PubHealth", "Visual", "FAA-DOD","Other")

ggplot_list<-list()

for (r in recource) {
  classData_r <- classData[sapply(classData$Prot, function(x) any(grepl(r, unlist(strsplit(x, ","))))), ]
    
  ggplot_list[[length(ggplot_list)+1]]<- RowCounts(classData_r, paste("Protected Resource:", r))
  ggplot_list[[length(ggplot_list)+1]]<- RowCounts(classData_r, paste("Protected Resource:", r), mode = "SAP")
  ggplot_list[[length(ggplot_list)+1]]<- RowCountsFreq(classData, classData_r, paste("Frequency of Protected Resource:", r))
  ggplot_list[[length(ggplot_list)+1]]<- RowHist(classData_r, paste("Protected Resource:", r))
}
pdf_width <- 8.5  # Inches
pdf_height <- 11  # Inches

# Number of plots to display on each page
plots_per_page <- 8  # 4 down and 2 across

# Calculate the number of pages needed
total_plots <- length(ggplot_list)
total_pages <- ceiling(total_plots / plots_per_page)

# Start generating the PDF
pdf("./SavedFigs/SuppFigs.pdf", width = pdf_width, height = pdf_height)

# Loop through the pages
for (i in 1:total_pages) {
  start_plot <- (i - 1) * plots_per_page + 1
  end_plot <- min(start_plot + plots_per_page - 1, total_plots)
  
  # Arrange plots in a grid on the current page
  plot_list_subset <- ggplot_list[start_plot:end_plot]
  do.call(gridExtra::grid.arrange, c(plot_list_subset, ncol = 2))
}

# Close the final page and the PDF
dev.off()

```
